gs_config:
  button:
    toggle_record:
      color: danger
      command: '/gs/button.sh toggle_record'
    scan_wfb_channel:
      color: success
      command: '/gs/button.sh scan_wfb_channel'
    null:
      color: primary
      command: 'echo test'
    change_otg_mode:
      color: info
      command: '/gs/button.sh change_otg_mode'
    change_wifi_mode:
      color: info
      command: '/gs/button.sh change_wifi_mode'
    mount_extdisk:
      color: info
      command: '/gs/button.sh mount_extdisk'
    cleanup_record_files:
      color: warning
      command: '/gs/button.sh cleanup_record_files'
    toggle_stream:
      color: warning
      command: '/gs/button.sh toggle_stream'
    ummount_extdisk:
      color: warning
      command: '/gs/button.sh ummount_extdisk'
    apply_conf:
      color: danger
      command: '/gs/button.sh apply_conf'
    shutdown_gs:
      color: danger
      command: '/gs/button.sh shutdown_gs'
    reboot_gs:
      color: danger
      command: '/gs/button.sh reboot_gs'
    start_rescue:
      visible: false
      color: info
      command: 'systemctl start tftpd-hpa && systemd-run --unit=webuart /usr/local/bin/ttyd -p 83 -W picocom -b 115200 -l /dev/ttyS3'
    stop_rescue:
      visible: false
      color: info
      command: 'systemctl stop tftpd-hpa && systemctl stop webuart'
    # test_gs:
    #   visible: true
    #   color: primary
    #   command: 'echo test_gs'
  systeminfo:
    current_screen_mode: 'drm_info | grep -oP "Mode: \K.*"'
    # current_screen_mode: 'drm_info -j /dev/dri/card0 | jq -r ".\"\/dev\/dri\/card0\".crtcs[0].mode.name + \"@\" + (.\"\/dev\/dri\/card0\".crtcs[0].mode.vrefresh | tostring)"'
    otg_mode: 'cat /sys/kernel/debug/usb/fcc00000.dwc3/mode'
    wifi_mode: 'nmcli con | grep -oP "^\S+(?=.*wifi0)"'
    cpu_temp: 'echo $(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))'
    88x2eu_temp: '[ -d /proc/net/rtl88x2eu ] && cat /proc/net/rtl88x2eu/wlx*/thermal_state || echo "No RTL8812EU connected!"'
    network_info: "ip -o -4 addr show | awk '{print $2, $4}'"
    wifi_info: 'for nic in /sys/class/net/wlx*; do [ -d $nic ] && iw $(basename $nic) info; done'
    supported_screen_modes: 'pixelpilot --screen-mode-list'
    mem_info: 'free -m'
    disk_info: 'df -hT'
    # top10_cpu_usage: 'top -b -o +%CPU | head -n 17'
    kernel_info: 'uname -a'
    gs_release: 'cat /etc/gs-release'
  gs:
    path: /etc/gs.conf
    format: ini
  wfb:
    path: /etc/wifibroadcast.cfg
    format: ini
  wfb_default:
    path: /etc/default/wifibroadcast
    format: ini
  gs_config_files:
    - settings_webui.yaml
    - /etc/gs.conf
    # - /etc/wifibroadcast.cfg
    # - /etc/default/wifibroadcast
  plotter:
    json_stream_host: 127.0.0.1
    json_stream_port: 8103
    rssi_min: -80
    rssi_max: -40
    snr_min: 10
    snr_max: 30
    data_redundancy_min: 0
    data_redundancy_max: 6
    max_samples: 300
    socket_timeout: 6
    derivative_window: 4
    derivative_min: -1.0
    derivative_max: 1.0
    fec_rec_min: 0
    fec_rec_max: 10
    lost_min: 0
    lost_max: 5
    mbit_min: 0.0
    mbit_max: 16.0

drone_config:
  ssh:
    # host: '192.168.1.10'
    host: 10.5.0.10
    port: '22'
    username: root
    password: '12345'
  button:
    720p120:
      color: info
      command: 'cli -s .video0.size 1280x720 && cli -s .video0.fps 120 && killall -1 majestic'
    1080p60:
      color: info
      command: 'cli -s .video0.size 1920x1080 && cli -s .video0.fps 60 && killall -1 majestic'
    1080p90:
      color: info
      command: 'cli -s .video0.size 1920x1080 && cli -s .video0.fps 90 && killall -1 majestic'
    test:
      color: primary
      command: 'echo drone button test'
    restart_majestic:
      color: warning
      command: 'killall -1 majestic'
    restart_wfb:
      color: warning
      command: '/etc/init.d/S98wifibroadcast stop && /etc/init.d/S98wifibroadcast start &'
    reset_majestic:
      color: warning
      command: 'cp /rom/etc/majestic.yaml /etc/majestic.yaml'
    reset_wfb:
      color: warning
      command: 'cp /rom/etc/wfb.yaml /etc/wfb.yaml'
    shutdown_drone:
      color: danger
      command: 'poweroff'
    reboot_drone:
      color: danger
      command: 'reboot'
    firstboot_drone:
      color: danger
      command: 'firstboot &'
  quick_setting:
    majestic_res:
      color: primary
      command: "cli -s .video0.size {target_value} && killall -1 majestic"
      options: ["1280x720", "1920x1080", "2560x1440", "3840x2160"]
      tip: "Please enter the video resolution."
    majestic_fps:
      color: primary
      command: "cli -s .video0.fps {target_value} && killall -1 majestic"
      # command: "echo 'setfps 0 {target_value}' > /proc/mi_modules/mi_sensor/mi_sensor0"
      options: ["20", "30", "60", "90", "120"]
      tip: "Please enter the video frame rate."
    majestic_bitrate:
      color: primary
      command: "cli -s .video0.bitrate {target_value} && curl -s 'http://localhost/api/v1/set?video0.bitrate={target_value}'"
      options: ["2048", "4096", "6144", "8192", "10240"]
      tip: "Please enter the video bitrate."
    majestic_codec:
      color: primary
      command: "cli -s .video0.codec {target_value} && killall -1 majestic"
      options: ["h264", "h265"]
      tip: "Please enter the video codec."
    wfb_channel:
      color: danger
      command: "wfb-cli -s .wireless.channel {target_value} && /etc/init.d/S98wifibroadcast stop && /etc/init.d/S98wifibroadcast start &"
      options: ["36", "157", "161"]
      tip: "Please enter the WiFi channel."
    wfb_mcs:
      color: primary
      command: "wfb_tx_cmd 8000 set_radio -B 20 -G long -S 1 -L 1 -M {target_value}"
      options: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
      tip: "Please enter the WiFi MCS index."
    wfb_txpower:
      color: primary
      command: '[ "$(basename $(readlink /sys/class/net/wlan0/device/driver))" == "rtl88xxau" ] && iw wlan0 set txpower fixed "$(({target_value} * -100))" || iw wlan0 set txpower fixed "$(({target_value} * 50))"'
      options: ["1", "5", "15", "25", "35", "45"]
      tip: "Please enter the WiFi Tx power(0~63). Not recommend exceed 45 for RTL8812 CU/EU"
    wfb_bandwidth:
      color: danger
      command: "wfb-cli -s .wireless.mode {target_value} && channel=$(iw dev wlan0 info | awk '/channel/ {{print $2}}') && iw wlan0 set channel $channel {target_value}"
      # command: "wfb-cli -s .wireless.mode {target_value} && /etc/init.d/S98wifibroadcast stop && /etc/init.d/S98wifibroadcast start &"
      options: ["HT20", "HT40+"]
      tip: "Please enter the WiFi bandwidth."
  systeminfo:
    hardware_info: 'fw_printenv | grep "soc=\|sensor="'
    cpu_temp: 'cat /sys/devices/virtual/mstar/msys/TEMP_R'
    88x2eu_temp: '[ -d /proc/net/rtl88x2eu ] && cat /proc/net/rtl88x2eu/wlx*/thermal_state'
    network_info: "ip -o -4 addr show | awk '{print $2, $4}'"
    wifi_info: 'printf "Driver: " && basename $(readlink /sys/class/net/wlan0/device/driver) && iw wlan0 info'
    mem_info: 'free -m'
    disk_info: 'df -hT'
    # top10_cpu_usage: 'top -b -n 1 | head -n 14'
    kernel_info: 'uname -a'
    os_release: 'cat /etc/os-release'
  majestic:
    path: /etc/majestic.yaml
    format: yaml
  wfb:
    path: /etc/wfb.yaml
    format: yaml
  wfb_legency:
    path: /etc/wfb.conf
    format: ini
  datalink_legency:
    path: /etc/datalink.conf
    format: ini
  telemetry_legency:
    path: /etc/telemetry.conf
    format: ini

wfb_key_pair:
  default:
    name: Default
    gs: u7ftboOkaoqbihKg+Y7OK9yXhwW4IEcBsghfooyse0YOBcSKYZX7cJIcdHpm6DwC5kC9a761slFTepiidBaiYw==
    drone: u7ftboOkaoqbihKg+Y7OK9yXhwW4IEcBsghfooyse0YOBcSKYZX7cJIcdHpm6DwC5kC9a761slFTepiidBaiYw==
  key1:
    name: ''
    gs: ''
    drone: ''
  key2:
    name: ''
    gs: ''
    drone: ''
  key3:
    name: ''
    gs: ''
    drone: ''
  key4:
    name: ''
    gs: ''
    drone: ''
  key5:
    name: ''
    gs: ''
    drone: ''
