gs_config:
  button:
    toggle_record:
      color: danger
      command: "/gs/button.sh toggle_record"
    scan_wfb_channel:
      color: success
      command: "/gs/button.sh scan_wfb_channel"
    null:
      color: primary
      command: "echo test"
    change_otg_mode:
      color: info
      command: "/gs/button.sh change_otg_mode"
    change_wifi_mode:
      color: info
      command: "/gs/button.sh change_wifi_mode"
    mount_extdisk:
      color: info
      command: "/gs/button.sh mount_extdisk"
    cleanup_record_files:
      color: warning
      command: "/gs/button.sh cleanup_record_files"
    toggle_stream:
      color: warning
      command: "/gs/button.sh toggle_stream"
    ummount_extdisk:
      color: warning
      command: "/gs/button.sh ummount_extdisk"
    apply_conf:
      color: danger
      command: "/gs/button.sh apply_conf"
    shutdown_gs:
      color: danger
      command: "/gs/button.sh shutdown_gs"
    reboot_gs:
      color: danger
      command: "/gs/button.sh reboot_gs"
    test_gs:
      color: primary
      command: "echo test_gs"
  gs:
    path: /etc/gs.conf
    format: ini
  wfb:
    path: /etc/wifibroadcast.cfg
    format: ini
  wfb_default:
    path: /etc/default/wifibroadcast
    format: ini

drone_config:
  ssh:
    # host: "192.168.1.10"
    host: 10.5.0.10
    port: '22'
    username: root
    password: '12345'
  button:
    restart_majestic:
      color: info
      command: "killall -1 majestic"
    restart_wfb:
      color: info
      command: "/etc/init.d/S98wifibroadcast stop && /etc/init.d/S98wifibroadcast start &"
  majestic:
    path: /etc/majestic.yaml
    format: yaml
  wfb:
    path: /etc/wfb.yaml
    format: yaml
  wfb_legency:
    path: /etc/wfb.conf
    format: ini
  datalink_legency:
    path: /etc/datalink.conf
    format: ini
  telemetry_legency:
    path: /etc/telemetry.conf
    format: ini

wfb_key_pair:
  default:
    name: Default
    gs: u7ftboOkaoqbihKg+Y7OK9yXhwW4IEcBsghfooyse0YOBcSKYZX7cJIcdHpm6DwC5kC9a761slFTepiidBaiYw==
    drone: u7ftboOkaoqbihKg+Y7OK9yXhwW4IEcBsghfooyse0YOBcSKYZX7cJIcdHpm6DwC5kC9a761slFTepiidBaiYw==
  key1:
    name: ''
    gs: ''
    drone: ''
  key2:
    name: ''
    gs: ''
    drone: ''
  key3:
    name: ''
    gs: ''
    drone: ''
  key4:
    name: ''
    gs: ''
    drone: ''
  key5:
    name: ''
    gs: ''
    drone: ''
