gs_config_files:
  gs:
    path: fakeroot/etc/gs.conf
    format: sh
  wfb:
    path: fakeroot/etc/wifibroadcast.cfg
    format: ini
  wfb_default:
    path: fakeroot/etc/default/wifibroadcast
    format: sh

drone_config_files:
  majestic:
    path: "fakeroot/etc/majestic.yaml"
    format: yaml
  wfb:
    path: "fakeroot/etc/wfb.yaml"
    format: yaml
  wfb_legency:
    path: "fakeroot/etc/wfb.conf"
    format: sh
  datalink_legency:
    path: "fakeroot/etc/datalink.conf"
    format: sh
  telemetry_legency:
    path: "fakeroot/etc/telemetry.conf"
    format: sh

