gs_config_files:
  gs:
    path: fakeroot/etc/gs.conf
    format: ini
  wfb:
    path: fakeroot/etc/wifibroadcast.cfg
    format: ini
  wfb_default:
    path: fakeroot/etc/default/wifibroadcast
    format: ini

drone_config_files:
  majestic:
    path: "fakeroot/etc/majestic.yaml"
    format: yaml
  wfb:
    path: "fakeroot/etc/wfb.yaml"
    format: yaml
  wfb_legency:
    path: "fakeroot/etc/wfb.conf"
    format: ini
  datalink_legency:
    path: "fakeroot/etc/datalink.conf"
    format: ini
  telemetry_legency:
    path: "fakeroot/etc/telemetry.conf"
    format: ini

drone_config:
  # host: 192.168.1.10
  host: 10.5.0.10
  username: root
  password: 12345
