gs_config_files:
  gs:
    path: /etc/gs.conf
    format: sh
  wfb:
    path: /etc/wifibroadcast.cfg
    format: ini
  wfb_default:
    path: /etc/default/wifibroadcast
    format: sh

drone_config_files:
  majestic:
    path: "/etc/majestic.yaml"
    format: yaml
  wfb:
    path: "/etc/wfb.yaml"
    format: yaml
  wfb_legency:
    path: "/etc/wfb.conf"
    format: sh
  datalink_legency:
    path: "/etc/datalink.conf"
    format: sh
  telemetry_legency:
    path: "/etc/telemetry.conf"
    format: sh

