BLUE_LED_PIN: '''12'''
BLUE_LED_drive: '''push-pull'''
BTN_CD_PIN: '''16'''
BTN_CD_long_press: ''''''
BTN_CD_single_press: ''''''
BTN_CL_PIN: '''13'''
BTN_CL_long_press: ''''''
BTN_CL_single_press: ''''''
BTN_CM_PIN: ''''''
BTN_CM_long_press: ''''''
BTN_CM_single_press: ''''''
BTN_CR_PIN: '''11'''
BTN_CR_long_press: ''''''
BTN_CR_single_press: ''''''
BTN_CU_PIN: '''18'''
BTN_CU_long_press: ''''''
BTN_CU_single_press: ''''''
BTN_Q1_PIN: '''32'''
BTN_Q1_long_press: '''cleanup_record_files'''
BTN_Q1_single_press: '''toggle_record'''
BTN_Q2_PIN: '''38'''
BTN_Q2_long_press: '''change_otg_mode'''
BTN_Q2_single_press: '''scan_wfb_channel'''
BTN_Q3_PIN: '''40'''
BTN_Q3_long_press: '''change_wifi_mode'''
BTN_Q3_single_press: ''''''
GREEN_LED_PIN: '''15'''
GREEN_LED_drive: '''push-pull'''
Hotspot_Password: '''12345678'''
Hotspot_SSID: '''SBC-GS'''
Hotspot_ip: '''192.168.4.1/24'''
REC_Dir: '''/Videos'''
REC_FPS: '''60'''
RED_LED_PIN: '''22'''
RED_LED_drive: '''push-pull'''
WIFI_Encryption: '''wpa-psk'''
WIFI_Password: ''''''
WIFI_SSID: '''OpenIPC'''
WIFI_mode: '''hotspot'''
append_kernel_cmdline: ''''''
br0_fixed_ip: '''192.168.1.20/24'''
br0_fixed_ip2: '''10.0.36.254/24'''
disable_integrated_wifi: '''no'''
dtbo_enable_list: '''pwm14-m0 uart3-m0 i2c4-m0'''
enable_external_antenna: '''no'''
fan_PWM_MAX_duty_cycle: '''80'''
fan_PWM_MIN_duty_cycle: '''0'''
fan_PWM_channel: '''0'''
fan_PWM_chip: '''14'''
fan_PWM_frequency: '''25000'''
fan_PWM_polarity: '''normal'''
fan_PWM_step_duty_cycle: '''5'''
fan_overheat_temperature: '''70'''
fan_service_enable: '''yes'''
fan_target_temperature: '''50'''
fan_target_temperature_deviation: '''3'''
gadget_net_fixed_ip: '''192.168.2.20/24'''
gps_uart: '''ttyS3'''
gps_uart_baudrate: '''38400'''
max_resolution_4k: '''no'''
monitor_8812eu_temperature: '''yes'''
msposd_gs_ahi: '''0'''
msposd_gs_fps: '''20'''
msposd_gs_method: '''tunnel'''
msposd_gs_port: '''14551'''
osd_config_file: ''''''
osd_enable: '''yes'''
osd_fps: '''20'''
osd_type: '''mavlink'''
otg_mode: '''device'''
otg_mode_LED_PIN: '''GREEN_LED_PIN'''
otg_mode_LED_drive: '''GREEN_LED_drive'''
rec_dir_freespace_min: '''1000'''
record_on: ''''''
rootfs_reserved_space: '''1500'''
rtl8812eu_temperature_offset: '''-1'''
screen_mode: ''''''
system_wide_screen_mode: '''no'''
temperature_monitor_cycle: '''10'''
use_external_rtc: '''no'''
use_gps: '''no'''
video_codec: '''h265'''
video_on_boot: '''yes'''
video_player: '''pixelpilot'''
wfb_bandwidth: '''20'''
wfb_channel: '''161'''
wfb_integrated_wnic: ''''''
wfb_key: '''/etc/gs.key'''
wfb_link_id: '''7669206'''
wfb_mode: '''standalone'''
wfb_outgoing_ip: '''224.0.0.1'''
wfb_outgoing_port_mavlink: '''14550'''
wfb_outgoing_port_video: '''5600'''
wfb_region: '''00'''
wfb_stream_id_mavlink: '''16'''
wfb_stream_id_tunnel: '''32'''
wfb_stream_id_video: '''0'''
wfb_txpower: ''''''
